'use strict';
const places=[
{id:'riverside',title:'Take the scenic route',category:'outdoors',label:'OUTDOORS & OPEN SKIES',image:'countryside.jpg',time:'1–2 hours · Gentle walking',description:'Follow the River Alder through open meadows, shady banks, and the quieter side of town.',detail:'Begin at the old stone bridge and follow the riverside path towards Mill Meadow. Pack a picnic and take the return path through the orchard. The meadow can be muddy after rain; sturdy footwear is a good idea.'},
{id:'old-town',title:'Wander a little further back',category:'culture',label:'HISTORY & HIDDEN CORNERS',image:'village.jpg',time:'45–60 minutes · Town centre',description:'Honey-coloured cottages, cobbled lanes, and centuries of stories hiding in plain sight.',detail:'Start in the market square, take a turn into Weaver’s Lane, and look for the carved dates above the old doorways. Finish at the heritage rooms for a glimpse of the people and trades that shaped the town.'},
{id:'market',title:'A taste of the local life',category:'food',label:'GOOD FOOD & INDEPENDENT SPIRIT',image:'street.jpg',time:'1–2 hours · Browse & unwind',description:'Freshly baked treats, proper coffee, and small shops with big personalities.',detail:'Make a morning of the market square. Browse the bookshop, find something handmade, and pause for a pastry at the bakery. On market days, local growers and makers bring even more colour to the square.'}
];
const events=[
{id:'harvest',day:'10',month:'OCT',title:'The autumn makers’ market',category:'community',tag:'Food, craft & community',meta:'Market Square · 10:00–15:00 · Free entry',description:'Meet local makers, stock up on seasonal produce, and find something made with care. A relaxed outdoor market for all ages.',start:'20261010T100000',end:'20261010T150000',location:'Market Square, Alderwick'},
{id:'music',day:'17',month:'OCT',title:'An evening of acoustic stories',category:'arts',tag:'Music & a little magic',meta:'The Old Assembly Hall · 19:00–21:00 · Free entry',description:'An intimate evening of acoustic songs and storytelling in the old hall. Doors open at 18:30; seating is first come, first served.',start:'20261017T190000',end:'20261017T210000',location:'The Old Assembly Hall, Alderwick'},
{id:'walk',day:'24',month:'OCT',title:'Walk the changing seasons',category:'community',tag:'Fresh air & familiar faces',meta:'Old Stone Bridge · 10:00–12:00 · Free entry',description:'Join a gentle two-hour community ramble along the river and into the orchard. Bring water and shoes for muddy paths. Children should be accompanied by an adult.',start:'20261024T100000',end:'20261024T120000',location:'Old Stone Bridge, Alderwick'}
];
const $=s=>document.querySelector(s);let saved=[];let storageAvailable=true;
try{const raw=JSON.parse(localStorage.getItem('alderwick-day')||'[]');saved=Array.isArray(raw)?raw.filter(id=>places.some(p=>p.id===id)):[];}catch{storageAvailable=false;}
let placeFilter='all',eventFilter='all';let toastTimer;
function notify(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),2800);}
function persist(){try{localStorage.setItem('alderwick-day',JSON.stringify(saved));}catch{storageAvailable=false;}$('.plan-count').textContent=saved.length;renderPlaces();renderPlanner();}
function togglePlace(id){if(!places.some(p=>p.id===id))return;const exists=saved.includes(id);saved=exists?saved.filter(x=>x!==id):[...saved,id];persist();notify(exists?'Removed from your day.':storageAvailable?'Added to your day.':'Added for this visit. Device storage is unavailable.');document.querySelectorAll('[data-detail-save]').forEach(b=>b.textContent=saved.includes(id)?'Remove from my day':'Add to my day');}
function renderPlaces(){const term=$('#place-search').value.trim().toLowerCase();const shown=places.filter(p=>(placeFilter==='all'||p.category===placeFilter)&&`${p.title} ${p.description} ${p.label}`.toLowerCase().includes(term));$('#place-grid').innerHTML=shown.map(p=>`<article class="place-card"><button class="card-image" data-place-detail="${p.id}" aria-label="Read about ${p.title}"><img src="assets/${p.image}" alt="${p.category==='outdoors'?'A footpath winding through green meadows':p.category==='culture'?'Historic stone cottages lining a village lane':'Traditional shops and buildings around a market square'}" loading="lazy"><span class="image-label">${p.label}</span></button><div class="card-info"><h3>${p.title}</h3><p>${p.description}</p><div class="card-bottom"><span>${p.time}</span><button class="save-place" data-save="${p.id}" aria-pressed="${saved.includes(p.id)}">${saved.includes(p.id)?'✓ Saved':'+ My day'}</button></div></div></article>`).join('');$('#place-empty').hidden=shown.length>0;$('#place-count').textContent=`${shown.length} ${shown.length===1?'discovery':'discoveries'} to make your own`;}
function renderEvents(){$('#event-list').innerHTML=events.filter(e=>eventFilter==='all'||e.category===eventFilter).map(e=>`<article class="event-row"><div class="event-date"><strong>${e.day}</strong>${e.month} 2026</div><div><span class="event-tag">${e.tag}</span><h3>${e.title}</h3><p>${e.meta}</p></div><button data-event="${e.id}" aria-label="Details for ${e.title}">Event details</button></article>`).join('');}
function renderPlanner(){$('#planner-items').innerHTML=saved.length?saved.map((id,i)=>{const p=places.find(p=>p.id===id);return `<div class="planner-item"><div><strong>${i+1}. ${p.title}</strong><small>${p.time}</small></div><button data-save="${id}" aria-label="Remove ${p.title}">Remove</button></div>`;}).join(''):'<p style="padding:25px 0">Your day is wide open. Add a discovery from the town guide, or start with all three.</p><button class="button green" id="suggest-day">Add a leisurely town day</button>';$('#download-plan').disabled=!saved.length;$('#download-plan').style.opacity=saved.length?'1':'.45';$('#clear-plan').hidden=!saved.length;$('#planner-status').textContent=storageAvailable?'':'Your browser cannot save this list permanently. Download it to keep a copy.';}
function openDialog(id){$(id).showModal();document.body.style.overflow='hidden';}
document.querySelectorAll('dialog').forEach(d=>{d.addEventListener('close',()=>{document.body.style.overflow='';});d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});});
function download(filename,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const escapeICS=s=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');
function downloadEvent(id){const e=events.find(e=>e.id===id);const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Alderwick//Visitor Guide//EN','BEGIN:VEVENT',`UID:${e.id}-2026@alderwick.example`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART:${e.start}`,`DTEND:${e.end}`,`SUMMARY:${escapeICS(e.title)}`,`LOCATION:${escapeICS(e.location)}`,`DESCRIPTION:${escapeICS(e.description)} (Local town time.)`,'END:VEVENT','END:VCALENDAR'];download(`alderwick-${e.id}.ics`,lines.join('\r\n')+'\r\n','text/calendar;charset=utf-8');notify('Calendar file downloaded.');}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.matches('[data-close]'))b.closest('dialog').close();if(b.matches('[data-save]'))togglePlace(b.dataset.save);if(b.matches('[data-planner]')){renderPlanner();openDialog('#planner-dialog');}if(b.matches('[data-place-filter]')){placeFilter=b.dataset.placeFilter;document.querySelectorAll('[data-place-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b);});renderPlaces();}if(b.matches('[data-event-filter]')){eventFilter=b.dataset.eventFilter;document.querySelectorAll('[data-event-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b);});renderEvents();}if(b.matches('[data-place-detail]')){const p=places.find(p=>p.id===b.dataset.placeDetail);$('#detail-content').innerHTML=`<img class="detail-photo" src="assets/${p.image}" alt="${p.title}"><p class="eyebrow">${p.label}</p><h2 id="detail-title">${p.title}</h2><p>${p.detail}</p><p class="detail-meta">${p.time}</p><button class="button green" data-save="${p.id}" data-detail-save>${saved.includes(p.id)?'Remove from my day':'Add to my day'}</button>`;openDialog('#detail-dialog');}if(b.matches('[data-event]')){const event=events.find(x=>x.id===b.dataset.event);$('#detail-content').innerHTML=`<p class="eyebrow">${event.day} ${event.month} 2026 · ${event.tag}</p><h2 id="detail-title">${event.title}</h2><p>${event.description}</p><p class="detail-meta">${event.meta}</p><button class="button green" data-calendar="${event.id}">Add to calendar</button><p class="detail-meta" style="margin-top:15px">Downloads an .ics file. Times are local to the town.</p>`;openDialog('#detail-dialog');}if(b.matches('[data-calendar]'))downloadEvent(b.dataset.calendar);if(b.id==='suggest-day'){saved=places.map(p=>p.id);persist();notify('A lovely little day, ready to go.');}if(b.matches('[data-gallery]')){galleryIndex=Number(b.dataset.gallery);renderGallery();openDialog('#gallery-dialog');}});
$('#place-search').addEventListener('input',renderPlaces);
$('.menu-toggle').addEventListener('click',()=>{const open=$('#navigation').classList.toggle('open');$('.menu-toggle').setAttribute('aria-expanded',open);});
$('#navigation').addEventListener('click',e=>{if(e.target.closest('a')){$('#navigation').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false');}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){$('#navigation').classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false');}if($('#gallery-dialog').open&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();galleryIndex=(galleryIndex+(e.key==='ArrowRight'?1:2))%3;renderGallery();}});
$('#clear-plan').addEventListener('click',()=>{saved=[];persist();notify('Your day planner is clear.');});
$('#download-plan').addEventListener('click',()=>{if(!saved.length)return;download('my-day-in-alderwick.txt','MY DAY IN ALDERWICK\n\n'+saved.map((id,i)=>{const p=places.find(p=>p.id===id);return `${i+1}. ${p.title}\n${p.time}\n${p.detail}`;}).join('\n\n')+'\n\nBring comfortable shoes and leave a little room for discovery.\n','text/plain;charset=utf-8');$('#planner-status').textContent='Your day plan has been downloaded.';});
const gallery=[{file:'village.jpg',caption:'The quiet corners · Photograph by Rob Farrow',alt:'Honey-coloured cottages on West Street in Castle Combe'},{file:'countryside.jpg',caption:'A breath of fresh air · Photograph by Ian Capper',alt:'A winding footpath through green countryside on the South Downs Way'},{file:'street.jpg',caption:'Stories in every stone · Photograph by Colin Smith',alt:'Historic market place in Chipping Norton'}];let galleryIndex=0;
function renderGallery(){const g=gallery[galleryIndex];$('#gallery-image').src='assets/'+g.file;$('#gallery-image').alt=g.alt;$('#gallery-caption').textContent=g.caption+' · '+(galleryIndex+1)+'/3';}
$('#gallery-prev').addEventListener('click',()=>{galleryIndex=(galleryIndex+2)%3;renderGallery();});$('#gallery-next').addEventListener('click',()=>{galleryIndex=(galleryIndex+1)%3;renderGallery();});
$('#year').textContent=new Date().getFullYear();$('.plan-count').textContent=saved.length;renderPlaces();renderEvents();renderPlanner();

$('#open-credits').addEventListener('click',()=>openDialog('#credits-dialog'));
